### ISSUE TITLE
License to use

### ISSUE THREAD

**Issue by vinhnx** [daniel211/LunarCalendarFunctionsInOBJC#1]
Hi @daniel211 , cảm ơn vì đã viết module này. Hiện tại mình có ý tưởng muốn sử dụng source code này của bạn cho 1  project. 

Cho mình hỏi, bạn có thể đặt license cho nó được không? Nếu MIT thì mình có thể sử dụng. 

Thanks!

**Comment by daniel211** [comment]
Hi @vinhnx , rất vui vì bạn thấy hứng thú và sử dụng src này. Mình đã update license rồi.

Happy coding :)
